export const ICON = {
  LIGHTMODE: "light_mode",
  DARKMODE: "dark_mode",
  CHAT: "chat",
  NOTIFICATIONS: "notifications",
  HEART: "favorite",
  PLUS: "add",
  SEND: "send",
  BACK: "chevron_left",
  CLOSE: "close",
  TRASH: "delete",
  HOME: "home",
  SEARCH: "search",
  ADD_BOX: "add_box",
  CHANNEL: "list_alt",
  PASSWORD: "password",
  LOGOUT: "logout",
  EDIT: "edit",
  CHAT_BUBBLE: "chat_bubble",
  PERSON_ADD: "person_add",
  PERSON_CHECK: "person_check",
  SIZE: {
    SMALL: 24,
    MEDIUM: 32,
    LARGE: 52,
  },
};
